<?php
if (isset($_GET['locale'])) {
    $lan = $_GET['locale'];
    $this->session->set("locale", $lan);
}

?>
<div class="mt-3">
    <form id="myform" method="GET" action="">
        <select name='locale' id="change" value="" style='position: relative' onchange="this.form.submit()">
            <option value="<?php echo $this->session->get("locale"); ?>"><?php echo $this->session->get("locale"); ?></option>
            <option value="Hindi">Hindi</option>
            <option value="English">English</option>
            <option value="Japanese">Japanese</option>
            <option value="French">French</option>
            <option value="Dutch">Dutch</option>
        </select>
    </form>
</div>
<h2><?php echo  $t->_('sign up') ?></h2>
<?php echo $this->tag->linkTo(["login/index",  $t->_("login here"), "class" => "btn btn-lg bg-dark text-muted mx-2"]);

?>
<?php echo $this->tag->form("signup/register"); ?>

<p>
    <label for="name"><?php echo  $t->_('Name') ?></label>
    <?php echo $this->tag->textField("name"); ?>
</p>

<p>
    <label for="email"><?php echo  $t->_('E-Mail') ?></label>
    <?php echo $this->tag->emailField("email"); ?>
</p>

<p>
    <label for="psaaword"><?php echo  $t->_('PASSWORD') ?></label>
    <?php echo $this->tag->passwordField("password"); ?>
</p>

<p>
    <label for="role"><?php echo  $t->_('ROLE') ?></label>
    <select name="role" id="role">
        <option value="admin"><?php echo  $t->_('admin') ?></option>
        <option value="manager"><?php echo  $t->_('manager') ?></option>
        <option value="user"><?php echo  $t->_('user') ?></option>
    </select>
</p>

<p>
    <label for="status"><?php echo  $t->_('STATUS') ?></label>
    <?php echo $this->tag->textField("status"); ?>
</p>

<p>
    <?php echo $this->tag->submitButton("Register"); ?>
</p>

</form>